# Conflict Prediction

In this project our aim was to predict and analyse early signs of brewing tension. We used data from the global economy. We selected social, political, and economic factors to look at.

In [3]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

url = 'https://raw.githubusercontent.com/chekirou/International-conflict-prediction/master/data/actual.csv'

In [4]:
df = pd.read_csv(url)

In [5]:
csv1 = pd.read_csv('/Users/yasmeenmahomedy2/code/yasmeeenm/conflict_analysis/old_datasets/csv1.csv')
csv2 = pd.read_csv('/Users/yasmeenmahomedy2/code/yasmeeenm/conflict_analysis/old_datasets/csv2.csv')
csv3 = pd.read_csv('/Users/yasmeenmahomedy2/code/yasmeeenm/conflict_analysis/old_datasets/csv3.csv')
csv4 = pd.read_csv('/Users/yasmeenmahomedy2/code/yasmeeenm/conflict_analysis/old_datasets/csv4.csv')
csv5 = pd.read_csv('/Users/yasmeenmahomedy2/code/yasmeeenm/conflict_analysis/old_datasets/csv5.csv')
csv6 = pd.read_csv('/Users/yasmeenmahomedy2/code/yasmeeenm/conflict_analysis/old_datasets/csv6.csv')
csv_pov = pd.read_csv('/Users/yasmeenmahomedy2/code/yasmeeenm/conflict_analysis/other peoples notebooks/poverty_df.csv')

In [6]:
csv1['CountryYear'] = csv1['Country']+csv1['Year'].astype(str)
csv2['CountryYear'] = csv2['Country']+csv2['Year'].astype(str)
csv3['CountryYear'] = csv3['Country']+csv3['Year'].astype(str)
csv4['CountryYear'] = csv4['Country']+csv4['Year'].astype(str)
csv5['CountryYear'] = csv5['Country']+csv5['Year'].astype(str)
csv6['CountryYear'] = csv6['Country']+csv6['Year'].astype(str)

In [7]:
csv_12 = pd.merge(csv1,csv2,on='CountryYear',how='outer')
csv_123 = pd.merge(csv_12,csv3,on='CountryYear',how='outer')
csv_1234 = pd.merge(csv_123,csv4,on='CountryYear',how='outer')
csv_12345 = pd.merge(csv_1234,csv5,on='CountryYear',how='outer')
csv_full = pd.merge(csv_12345,csv6,on='CountryYear',how='outer')

csv_full

/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_74067/3997445115.py:3: FutureWarning: Passing 'suffixes' which cause duplicate columns {'Code_x', 'Year_x', 'ContinentCode_x', 'Country_x'} in the result is deprecated and will raise a MergeError in a future version.
  csv_1234 = pd.merge(csv_123,csv4,on='CountryYear',how='outer')
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_74067/3997445115.py:5: FutureWarning: Passing 'suffixes' which cause duplicate columns {'Code_x', 'Year_x', 'ContinentCode_x', 'Country_x'} in the result is deprecated and will raise a MergeError in a future version.
  csv_full = pd.merge(csv_12345,csv6,on='CountryYear',how='outer')

,Country_x,Code_x,ContinentCode_x,Year_x,Military spending percent of total government spending,Arms imports million constant U.S. dollars,Cost of living index world average = 100,Food price index world average = 100,Housing and utilities price index world average = 100,Healthcare price index world average = 100,...,Security threats index 0 (low) - 10 (high),Factionalized elites index 0 (low) - 10 (high),Group grievance index 0 (low) - 10 (high),Economic decline index 0 (low) - 10 (high),Uneven economic development index 0 (low) - 10 (high),State legitimacy index 0 (high) - 10 (low),Human rights and rule of law index 0 (high) - 10 (low),Demographic pressures 0 (low) - 10 (high),Refugees and displaced persons index 0 (low) - 10 (high),External interventions index 0 (low) - 10 (high)
0,Afghanistan,AFG,AS,1960.0,NaN,40.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,AS,1961.0,NaN,56.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,AS,1962.0,NaN,64.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,AFG,AS,1963.0,NaN,40.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,AS,1964.0,NaN,56.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12559,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12560,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12561,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.1,10.0,9.1,9.9,8.0,9.9,9.9,9.9,9.9,9.4

In [8]:
conflicts = pd.read_csv('/Users/yasmeenmahomedy2/Downloads/civil_war_dataset - Combined, from 1970.csv')

In [9]:
def get_year(row):
    
    year_value = row['CountryYear'][-4:]
    
    return int(year_value)

In [10]:
def get_country(row):
    
    country_name = row['CountryYear'][:-4]

    return country_name

In [11]:
csv_full['year_all'] = csv_full.apply(lambda x: get_year(x),axis=1)

In [12]:
csv_full['country_all'] = csv_full.apply(lambda x: get_country(x), axis=1)

# Refining The Dataset

Here we remove smaller countries with insufficient data.

In [13]:
tiny_countries = ['Andorra','Antigua and Barbuda','Aruba','Belize','Bhutan','Brunei','Cape Verde','Comoros','Dominica','Kiribati',
                 'Micronesia','Montserrat','Palau','Saint Vincent and the Grenadines','Sao Tome and Principe','Solomon Islands','Taiwan',
                  'Tuvalu','Vanuatu','Euro area','Faroe Islands','Gibraltar','Macao','New Caledonia','San Marino','Norfolk Island','Holy See (Vatican City)']
csv_full = csv_full.set_index('country_all').drop(tiny_countries)
csv_full.reset_index(inplace=True)

In [14]:
csv_full['conflict_id'] =0
conflicts

csv_full[(csv_full['country_all']=='USA') & (csv_full['year_all']>1994)]

conflicts_1990 = conflicts[conflicts['Year']>1989]

In [15]:
my_list = []

def get_hist_data(country,year,lookback):
    
    early_year = lookback
    hist_data = csv_full[(csv_full['country_all']==country) & (csv_full['year_all'] <= (year -1)) & (csv_full['year_all'] > (year -1 - early_year))]
    while hist_data.shape[0] < lookback:
        early_year += 1
        
        hist_data = csv_full[(csv_full['country_all']==country) & (csv_full['year_all'] <= (year -1)) & (csv_full['year_all'] > (year -1 - early_year))]
    return hist_data

for index, row in conflicts_1990.iterrows():

    my_list.append(get_hist_data(row['Country'],row['Year'],5))


get_hist_data('USA',2010,10)    
    
len(my_list)

94

In [16]:
for i in range(len(my_list)):
    my_list[i]['conflict_id'] = i

/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_74067/729059741.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  my_list[i]['conflict_id'] = i

In [17]:
for i in range(len(my_list)):
    if len(my_list[i]) < 5:
        print(i)

In [18]:
final_df = pd.DataFrame(columns=my_list[50].columns)

In [19]:
for i in range(len(my_list)):
    
    final_df = pd.concat([final_df,my_list[i]])

In [20]:
final_df.shape

(470, 117)

# Dropping features

We drop features with 70% or more of the data missisng.

In [21]:
final_df.shape

(470, 117)

In [22]:
to_drop  = pd.DataFrame(final_df.isna().sum()/470)
len(to_drop)

117

In [23]:
to_drop_list = to_drop[to_drop[0]>0.7].index.values.tolist()
len(to_drop_list)

26

In [24]:
for i in to_drop_list:
    final_df.drop(columns=i, axis=1, inplace=True)

In [25]:
# final_df['CountryYear']

## Dropping data for the imputer

We will use an iterative imputer to fill in the remaining missing data.

In [26]:
bin_list = []
final_df

,country_all,Country_x,Code_x,ContinentCode_x,Year_x,Military spending percent of total government spending,Arms imports million constant U.S. dollars,Human Development Index (0 - 1),CountryYear,Country_y,...,Group grievance index 0 (low) - 10 (high),Economic decline index 0 (low) - 10 (high),Uneven economic development index 0 (low) - 10 (high),State legitimacy index 0 (high) - 10 (low),Human rights and rule of law index 0 (high) - 10 (low),Demographic pressures 0 (low) - 10 (high),Refugees and displaced persons index 0 (low) - 10 (high),External interventions index 0 (low) - 10 (high),year_all,conflict_id
6348,Rwanda,Rwanda,RWA,AF,1985.0,NaN,3.0,NaN,Rwanda1985,Rwanda,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1985,0
6349,Rwanda,Rwanda,RWA,AF,1986.0,NaN,2.0,NaN,Rwanda1986,Rwanda,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1986,0
6350,Rwanda,Rwanda,RWA,AF,1988.0,NaN,2.0,NaN,Rwanda1988,Rwanda,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1988,0
9657,Rwanda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rwanda1987,Rwanda,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1987,0
9658,Rwanda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rwanda1989,Rwanda,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1989,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3938,Kazakhstan,Kazakhstan,KAZ,AS,2017.0,3.45,214.0,0.813,Kazakhstan2017,Kazakhstan,...,7.6,6.4,4.2,8.3,7.3,4.5,3.0,4.2,2017,93
3939,Kazakhstan,Kazakhstan,KAZ,AS,2018.0,4.65,310.0,0.817,Kazakhstan2018,Kazakhstan,...,7.9,5.9,3.9,8.4,7.0,4.2,2.7,3.9,2018,93
3940,Kazakhstan,Kazakhstan,KAZ,AS,2019.0,5.25,312.0,0.817,Kazakhstan2019,Kazakhstan,...,8.1,5.6,3.6,8.5,6.7,3.9,2.4,3.6,2019,93
3941,Kazakhstan,Kazakhstan,KAZ,AS,2020.0,4.56,268.0,0.825,Kazakhstan2020,Kazakhstan,...,8.2,5.3,3.3,8.5,6.4,3.6,2.3,3.3,2020,93
3942,Kazakhstan,Kazakhstan,KAZ,AS,2021.0,NaN,NaN,NaN,Kazakhstan2021,Kazakhstan,...,8.0,5.5,3.2,8.2,6.7,4.1,2.1,3.0,2021,93

In [27]:
cleaner_df = final_df.drop(columns=bin_list)

In [28]:
cleaner_1985 = cleaner_df[cleaner_df['year_all']>1984]

imputer_drops = ['Country_x','Code_x','Country_y','Year_x','Year_y','Code_y','ContinentCode_y','ContinentCode_x','Christians as percent of the total population',
            'Shadow economy percent of GDP','Suicide mortality rate per 100000 population',
                 'Real interest rate: Bank lending rate minus inflation','Fiscal balance percent of GDP',
                 'Public spending on education percent of GDP','Government debt as percent of GDP',
                 'External debt percent of Gross National Income', 'GDP per capita Purchasing Power Parity',
                 'Banking system z-scores',
             'Factionalized elites index 0 (low) - 10 (high)', 'Security threats index 0 (low) - 10 (high)',
            'Economic decline index 0 (low) - 10 (high)','Human rights and rule of law index 0 (high) - 10 (low)',
            'External interventions index 0 (low) - 10 (high)',  'Uneven economic development index 0 (low) - 10 (high)',
            'State legitimacy index 0 (high) - 10 (low)',
            'Refugees and displaced persons index 0 (low) - 10 (high)', 'Demographic pressures 0 (low) - 10 (high)',
            'Refugee population',
             'Regulatory quality index (-2.5 weak; 2.5 strong)', 'Voice and accountability index (-2.5 weak; 2.5 strong)',
            'Military spending percent of total government spending ', 'Arms imports million constant U.S. dollars',
                
            'Capital investment as percent of GDP', 'Youth unemployment ages 15-24',
           'Food production index (2004-2006 = 100)', 'Foreign Direct Investment percent of GDP',
           'Population size in millions', 'Rural population percent of total population',
           'Population growth percent','Deaths of children under five years of age per 1000 live births',
            'Life expectancy in years',
            'Internet users percent of population',
           'Civil liberties index 7 (weak) - 1 (strong) ',
           'Globalization index (0-100)', 'Political globalization index (0-100)',
              'Labor freedom index (0-100)',
            'Economic freedom overall index (0-100)', 'Freedom from corruption index (0-100)',
               'Government spending as percent of GDP', 'Income from natural resources percent of GDP',
              'Human Development Index (0 - 1)', 'Inflation: percent change in the Consumer Price Index',
               'GDP per capita current U.S. dollars', 'Foreign aid and official development assistance received',
                'Unemployment rate',
#                  'Government effectiveness index (-2.5 weak; 2.5 strong)', 'Homicides per 100000 people', 'Death rate per 1000 people'
                 
                ]

In [29]:
cleaner_df = cleaner_df.drop(columns=imputer_drops)

In [30]:
(cleaner_1985.isna().sum()/cleaner_1985.shape[0]).sort_values()[40:60]

GDP per capita current U.S. dollars                         0.082979
Economic globalization index (0-100)                        0.095745
ContinentCode_x                                             0.097872
Foreign Direct Investment percent of GDP                    0.102128
Income from natural resources percent of GDP                0.102128
Refugee population                                          0.117021
Foreign aid and official development assistance received    0.123404
Labor force participation rate                              0.129787
Trade balance as percent of GDP                             0.148936
Inflation: percent change in the Consumer Price Index       0.148936
Internet users percent of population                        0.151064
Trade openness: exports plus imports as percent of GDP      0.155319
Unemployment rate                                           0.157447
Youth unemployment ages 15-24                               0.157447
Capital investment as percent of GDP                        0.165957
Human Development Index (0 - 1)                             0.172340
Government spending as percent of GDP                       0.189362
GDP per capita Purchasing Power Parity                      0.223404
External debt percent of Gross National Income              0.234043
Access to electricity percent of the population             0.287234
dtype: float64

In [31]:
cleaner_df['conflict_id']=cleaner_df['conflict_id'].astype(int)

In [32]:
cleaner_df

,country_all,CountryYear,Economic growth: the rate of change of real GDP,Labor force participation rate,Trade openness: exports plus imports as percent of GDP,Trade balance as percent of GDP,Rule of law index (-2.5 weak; 2.5 strong),Government effectiveness index (-2.5 weak; 2.5 strong),Control of corruption (-2.5 weak; 2.5 strong),Political stability index (-2.5 weak; 2.5 strong),Corruption Perceptions Index 100 = no corruption,Political rights index 7 (weak) - 1 (strong),Access to electricity percent of the population,Death rate per 1000 people,Economic globalization index (0-100),Social globalization index (0-100),Homicides per 100000 people,Group grievance index 0 (low) - 10 (high),year_all,conflict_id
6348,Rwanda,Rwanda1985,4.40,NaN,30.67,-9.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.05,19.89,14.37,NaN,NaN,1985,0
6349,Rwanda,Rwanda1986,5.47,NaN,32.74,-7.57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.48,21.05,14.53,NaN,NaN,1986,0
6350,Rwanda,Rwanda1988,4.50,NaN,24.22,-10.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.00,19.88,15.68,NaN,NaN,1988,0
9657,Rwanda,Rwanda1987,-0.02,NaN,26.59,-11.69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.52,20.75,15.15,NaN,NaN,1987,0
9658,Rwanda,Rwanda1989,-0.04,NaN,23.43,-11.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.54,18.82,15.76,NaN,NaN,1989,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3938,Kazakhstan,Kazakhstan2017,4.10,69.25,56.83,7.97,-0.47,-0.03,-0.82,0.03,31.0,7.0,100.0,7.15,52.59,69.83,5.0,7.6,2017,93
3939,Kazakhstan,Kazakhstan2018,4.10,70.13,63.53,11.72,-0.49,-0.01,-0.47,-0.05,31.0,7.0,100.0,7.14,52.96,68.69,NaN,7.9,2018,93
3940,Kazakhstan,Kazakhstan2019,4.50,70.08,64.86,8.02,-0.49,0.11,-0.26,-0.17,34.0,7.0,100.0,7.19,56.25,66.51,NaN,8.1,2019,93
3941,Kazakhstan,Kazakhstan2020,-2.50,69.20,56.22,4.23,-0.44,0.14,-0.36,-0.26,38.0,7.0,100.0,8.60,NaN,NaN,NaN,8.2,2020,93
3942,Kazakhstan,Kazakhstan2021,4.00,69.07,NaN,NaN,-0.49,0.06,-0.24,-0.25,37.0,NaN,NaN,NaN,NaN,NaN,NaN,8.0,2021,93

# Grouping the data

Group data by conflict ID

In [33]:
grouped_df = cleaner_df.groupby(by='conflict_id').mean()

/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_74067/2490057627.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  grouped_df = cleaner_df.groupby(by='conflict_id').mean()

In [34]:
grouped_df.columns

Index(['Economic growth: the rate of change of real GDP',
       'Labor force participation rate',
       'Trade openness: exports plus imports as percent of GDP',
       'Trade balance as percent of GDP',
       'Rule of law index (-2.5 weak; 2.5 strong)',
       'Government effectiveness index (-2.5 weak; 2.5 strong)',
       'Control of corruption (-2.5 weak; 2.5 strong)',
       'Political stability index (-2.5 weak; 2.5 strong)',
       'Corruption Perceptions Index 100 = no corruption',
       'Political rights index 7 (weak) - 1 (strong)',
       'Access to electricity percent of the population',
       'Death rate per 1000 people', 'Economic globalization index (0-100)',
       'Social globalization index (0-100)', 'Homicides per 100000 people',
       'Group grievance index 0 (low) - 10 (high)'],
      dtype='object')

# Create the control dataset

In [35]:
conflict_years = final_df['CountryYear']

In [36]:
csv4_after_1980 = csv_full[csv_full['year_all'] > 1985]
csv4_after_1980_noconflict = csv4_after_1980[csv4_after_1980.CountryYear.isin(conflict_years)==False]
csv4_after_1980.shape[0] - csv4_after_1980_noconflict.shape[0]

437

In [37]:
def slice_fn(sample):
    year = int(sample[-4:])
    words = [sample[:-4]+str(year-i-1) for i in range(4)]
    words.append(sample)
    return words

In [38]:
#change for sara

from itertools import chain

sample_list = []

control_sample = csv4_after_1980.sample(270,random_state=1776)

for index,row in control_sample.iterrows():
    sample_list.append(get_hist_data(row['country_all'],row['year_all'],5))

sample_full = sample_list[0]

for i in range(1,len(sample_list)):
    
    sample_full = pd.concat([sample_full,sample_list[i]])

In [39]:
id_list = list(range(95,365))*5
sample_full

,country_all,Country_x,Code_x,ContinentCode_x,Year_x,Military spending percent of total government spending,Arms imports million constant U.S. dollars,Cost of living index world average = 100,Food price index world average = 100,Housing and utilities price index world average = 100,...,Group grievance index 0 (low) - 10 (high),Economic decline index 0 (low) - 10 (high),Uneven economic development index 0 (low) - 10 (high),State legitimacy index 0 (high) - 10 (low),Human rights and rule of law index 0 (high) - 10 (low),Demographic pressures 0 (low) - 10 (high),Refugees and displaced persons index 0 (low) - 10 (high),External interventions index 0 (low) - 10 (high),year_all,conflict_id
3217,Hungary,Hungary,HUN,EU,2011.0,2.11,9.0,NaN,NaN,NaN,...,3.5,5.4,5.5,5.4,3.0,3.1,3.1,4.3,2011,0
3218,Hungary,Hungary,HUN,EU,2012.0,2.09,NaN,NaN,NaN,NaN,...,3.8,5.9,5.2,5.8,3.2,2.8,2.8,4.0,2012,0
3219,Hungary,Hungary,HUN,EU,2013.0,1.88,2.0,NaN,NaN,NaN,...,4.1,6.0,4.9,5.9,3.4,2.5,2.9,3.8,2013,0
3220,Hungary,Hungary,HUN,EU,2014.0,1.71,7.0,NaN,NaN,NaN,...,4.4,5.6,4.6,6.0,4.1,2.8,2.8,3.7,2014,0
3221,Hungary,Hungary,HUN,EU,2015.0,1.80,NaN,NaN,NaN,NaN,...,4.7,5.9,4.3,6.6,4.5,2.3,2.5,4.0,2015,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
554,Bangladesh,Bangladesh,BGD,AS,1985.0,NaN,63.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1985,0
555,Bangladesh,Bangladesh,BGD,AS,1986.0,NaN,4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1986,0
556,Bangladesh,Bangladesh,BGD,AS,1987.0,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1987,0
557,Bangladesh,Bangladesh,BGD,AS,1988.0,10.33,242.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1988,0
558,Bangladesh,Bangladesh,BGD,AS,1989.0,10.45,301.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1989,0

In [40]:
id_list = sorted(id_list)

In [41]:
sample_full['conflict_id'] = id_list
sample_full['country_all'].unique()

array(['Hungary', 'Slovenia', 'Kenya', 'Rwanda', 'Puerto Rico',
       'Botswana', 'Tonga', 'Angola', 'Mauritius', 'Turkey', 'France',
       'Tanzania', 'Sweden', 'Oman', 'Greece', 'Bahamas', 'Ireland',
       'Lebanon', 'Guatemala', 'Turkmenistan', 'Estonia', 'Lesotho',
       'Malta', 'Nepal', 'Luxembourg', 'Iraq', 'Honduras', 'Bahrain',
       'Morocco', 'Egypt', 'Moldova', 'Tajikistan', 'Afghanistan',
       'Central African Republic', 'Democratic Republic of the Congo',
       'Swaziland', 'Jamaica', 'North Macedonia', 'Equatorial Guinea',
       'Uzbekistan', 'Azerbaijan', 'Mozambique', 'Senegal', 'Italy',
       'Saint Lucia', 'Suriname', 'Costa Rica', 'Mexico', 'Maldives',
       'Nigeria', 'Uruguay', 'United Arab Emirates', 'Ukraine',
       'Palestine', 'Sierra Leone', 'Zambia', 'Hong Kong', 'Germany',
       'Poland', 'Brazil', 'Syria', 'Jordan', 'Lithuania', 'Argentina',
       'Guinea-Bissau', 'Namibia', 'Ghana', 'Somalia', 'Serbia',
       'North Korea', 'Cuba', 'Dominican Republic', 'Venezuela', 'Benin',
       'Yemen', 'Gambia', 'Norway', 'Gabon', 'Colombia', 'Samoa',
       'Cyprus', 'Mali', 'USA', 'Liberia', 'Papua New Guinea',
       'Kyrgyzstan', 'Niger', 'Finland', 'Bermuda', 'Portugal',
       'Pakistan', 'Armenia', 'Madagascar', 'Sri Lanka', 'Monaco',
       'Latvia', 'Kuwait', 'Guyana', 'Libya', 'South Africa',
       'Liechtenstein', 'Belgium', 'Croatia', 'Seychelles', 'Togo',
       'Zimbabwe', 'Iran', 'Netherlands', 'Ivory Coast', 'Indonesia',
       'Uganda', 'Russia', 'South Korea', 'Austria', 'Switzerland',
       'Denmark', 'India', 'Belarus', 'Burkina Faso', 'Fiji',
       'Kazakhstan', 'Burundi', 'Bosnia and Herzegovina', 'Israel',
       'United Kingdom', 'Djibouti', 'Eritrea', 'Algeria', 'Ecuador',
       'Ethiopia', 'Cambodia', 'Qatar', 'Czechia', 'Barbados', 'Japan',
       'New Zealand', 'Paraguay', 'Malaysia', 'Iceland', 'Saudi Arabia',
       'El Salvador', 'Bolivia', 'Chad', 'Vietnam', 'Nicaragua',
       'Bangladesh'], dtype=object)

In [42]:
control_groupedby = sample_full.groupby('conflict_id').mean()
control_groupedby

/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_74067/2170563677.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  control_groupedby = sample_full.groupby('conflict_id').mean()

,Year_x,Military spending percent of total government spending,Arms imports million constant U.S. dollars,Cost of living index world average = 100,Food price index world average = 100,Housing and utilities price index world average = 100,Healthcare price index world average = 100,Happiness Index 0 (unhappy) - 10 (happy),Human Development Index (0 - 1),Year_y,...,Factionalized elites index 0 (low) - 10 (high),Group grievance index 0 (low) - 10 (high),Economic decline index 0 (low) - 10 (high),Uneven economic development index 0 (low) - 10 (high),State legitimacy index 0 (high) - 10 (low),Human rights and rule of law index 0 (high) - 10 (low),Demographic pressures 0 (low) - 10 (high),Refugees and displaced persons index 0 (low) - 10 (high),External interventions index 0 (low) - 10 (high),year_all
conflict_id,,,,,,,,,,,,,,,,,,,,,
95,2013.0,1.918,6.000000,NaN,NaN,NaN,NaN,4.7900,0.8304,2013.0,...,4.880000,4.100000,5.760000,4.900000,5.94,3.640000,2.700000,2.820000,3.960000,2013.0
96,1998.0,2.882,10.600000,NaN,NaN,NaN,NaN,NaN,0.8064,1998.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1998.0
97,2002.0,6.804,12.000000,NaN,NaN,NaN,NaN,NaN,0.4566,2002.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2002.0
98,1984.0,NaN,4.333333,NaN,NaN,NaN,NaN,NaN,NaN,1983.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1983.0
99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1984.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1984.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,2016.0,4.100,20.250000,53.79,68.300,35.969,48.48,5.8200,0.6916,2016.0,...,8.060000,6.240000,5.440000,8.580000,6.80,6.020000,6.460000,3.960000,5.960000,2016.0
361,2007.0,6.150,9.200000,NaN,NaN,NaN,NaN,NaN,0.4482,2007.0,...,3.933333,5.833333,6.066667,7.166667,5.80,5.866667,7.133333,5.333333,5.566667,2007.0
362,2016.0,4.240,10.500000,73.82,86.250,72.933,59.68,6.0925,0.6628,2016.0,...,4.300000,6.320000,5.680000,6.520000,4.94,6.140000,6.880000,5.060000,5.560000,2016.0
363,2017.0,14.004,582.200000,167.52,171.324,232.165,186.30,7.2180,0.9038,2017.0,...,8.100000,9.900000,4.000000,6.680000,6.40,7.340000,5.760000,7.380000,7.620000,2017.0
364,1987.0,10.390,122.200000,NaN,NaN,NaN,NaN,NaN,NaN,1987.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1987.0

In [43]:
columns_to_keep = list(grouped_df.columns)

In [44]:
sample_full_clean = control_groupedby.drop(columns=[col for col in control_groupedby if col not in columns_to_keep])

# sample_full_clean.isna().sum()

sample_full_clean

,Economic growth: the rate of change of real GDP,Labor force participation rate,Trade openness: exports plus imports as percent of GDP,Trade balance as percent of GDP,Rule of law index (-2.5 weak; 2.5 strong),Government effectiveness index (-2.5 weak; 2.5 strong),Control of corruption (-2.5 weak; 2.5 strong),Political stability index (-2.5 weak; 2.5 strong),Corruption Perceptions Index 100 = no corruption,Political rights index 7 (weak) - 1 (strong),Access to electricity percent of the population,Death rate per 1000 people,Economic globalization index (0-100),Social globalization index (0-100),Homicides per 100000 people,Group grievance index 0 (low) - 10 (high)
conflict_id,,,,,,,,,,,,,,,,
95,2.066,52.592,166.372,6.376,0.572000,0.622,0.246000,0.728000,52.00,1.4,100.000,12.980,83.286,80.662,1.640000,4.100000
96,4.106,58.144,96.588,-2.418,1.073333,0.770,1.033333,1.146667,NaN,1.0,100.000,9.460,56.742,71.360,1.500000,NaN
97,2.592,72.750,55.608,-7.562,-0.917500,-0.700,-1.000000,-1.152500,19.75,4.4,17.958,12.054,42.778,29.306,3.400000,NaN
98,2.678,NaN,32.518,-9.968,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.056,21.210,14.446,NaN,NaN
99,2.022,NaN,99.982,1.846,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.780,NaN,54.868,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,4.600,69.248,64.680,-4.868,-1.174000,-0.498,-0.684000,-0.284000,32.80,3.0,91.592,6.852,45.460,59.208,7.166667,6.240000
361,3.184,49.402,56.676,-16.734,-0.220000,-0.376,-0.382000,-0.212000,33.00,2.4,49.766,8.374,44.210,46.212,NaN,5.833333
362,2.268,58.552,75.482,-17.300,-0.718000,-0.290,-0.478000,-0.158000,36.40,2.0,96.066,6.984,61.596,64.112,78.175000,6.320000
363,3.774,63.932,58.274,1.976,1.054000,1.324,0.904000,-0.894000,61.60,1.2,100.000,5.160,70.414,86.004,1.400000,9.900000
364,3.308,NaN,17.588,-6.974,NaN,NaN,NaN,NaN,NaN,4.2,NaN,11.662,19.638,12.956,NaN,NaN

In [45]:
# sample_full_clean

# sara_conflict = pd.read_csv('imputed_final_df.csv',index_col=0)
# sara_control = pd.read_csv('imputed_control.csv')


# test_sara_conflict_ali_control = pd.concat([sara_conflict,imputed_control_df])
# test_sara_control_ali_conflict = pd.concat([imputed_conflict_df,sara_control])

# Merging dataset and imputing all

In [46]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

imputer = IterativeImputer(max_iter=10, random_state=0, missing_values=np.nan)
imputer2 = IterativeImputer(max_iter=10, random_state=0, missing_values=np.nan)

grouped_df['target'] = 1
sample_full_clean['target'] = 0

numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']


full_dataset = pd.concat([grouped_df,sample_full_clean])

In [47]:
data_numeric = full_dataset.select_dtypes(include=numerics)

imputer.fit(data_numeric)
imputed_final_df = pd.DataFrame(imputer.transform(data_numeric),columns=full_dataset.columns)
imputed_final_df.head()

/Users/yasmeenmahomedy2/.pyenv/versions/3.10.6/envs/conflict_prediction/lib/python3.10/site-packages/sklearn/impute/_iterative.py:713: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

,Economic growth: the rate of change of real GDP,Labor force participation rate,Trade openness: exports plus imports as percent of GDP,Trade balance as percent of GDP,Rule of law index (-2.5 weak; 2.5 strong),Government effectiveness index (-2.5 weak; 2.5 strong),Control of corruption (-2.5 weak; 2.5 strong),Political stability index (-2.5 weak; 2.5 strong),Corruption Perceptions Index 100 = no corruption,Political rights index 7 (weak) - 1 (strong),Access to electricity percent of the population,Death rate per 1000 people,Economic globalization index (0-100),Social globalization index (0-100),Homicides per 100000 people,Group grievance index 0 (low) - 10 (high),target
0,2.862,68.268783,27.530,-10.098,-1.371218,-1.313885,-0.997020,-1.440434,21.181396,5.249038,3.415823,19.918,20.078000,15.098000,6.511650,7.776382,1.0
1,3.200,65.447974,44.086,-11.674,-0.755741,-0.862529,-0.723355,-1.206879,27.744979,3.200000,26.963813,12.480,36.974000,21.962000,6.665634,7.079117,1.0
2,3.308,64.137536,17.588,-6.974,-1.120072,-1.200600,-1.004051,-1.552569,21.854781,4.200000,20.475494,11.662,19.638000,12.956000,6.980996,7.808531,1.0
3,4.888,65.709782,32.680,-9.670,-1.022976,-1.136050,-0.887328,-1.321218,22.897702,3.200000,13.449053,14.434,17.994000,12.112000,6.497581,7.460993,1.0
4,-4.666,65.840000,85.330,-2.880,-0.242828,-0.196360,-0.202176,-0.746951,42.586463,3.823515,64.591686,9.238,53.553034,56.010697,5.000000,6.400380,1.0

In [54]:
imputed_final_df.describe()

,Economic growth: the rate of change of real GDP,Labor force participation rate,Trade openness: exports plus imports as percent of GDP,Trade balance as percent of GDP,Rule of law index (-2.5 weak; 2.5 strong),Government effectiveness index (-2.5 weak; 2.5 strong),Control of corruption (-2.5 weak; 2.5 strong),Political stability index (-2.5 weak; 2.5 strong),Corruption Perceptions Index 100 = no corruption,Political rights index 7 (weak) - 1 (strong),Access to electricity percent of the population,Death rate per 1000 people,Economic globalization index (0-100),Social globalization index (0-100),Homicides per 100000 people,Group grievance index 0 (low) - 10 (high),target
count,364.000000,364.000000,364.000000,364.000000,364.000000,364.000000,364.000000,364.000000,364.000000,364.000000,364.000000,364.000000,364.000000,364.000000,364.000000,364.000000,364.000000
mean,3.623288,60.417650,75.031806,-4.387188,-0.378347,-0.335484,-0.357303,-0.457010,35.770443,3.932197,70.224268,9.252353,50.579599,48.909664,8.319355,6.195628,0.258242
std,3.625383,10.857374,42.328780,12.313603,0.932807,0.905156,0.869489,0.970630,17.216801,2.110785,35.076287,4.285387,16.360993,21.573340,9.672540,1.779150,0.438270
min,-7.118000,34.070000,6.388000,-64.598000,-2.374000,-2.110000,-1.758000,-2.970000,8.000000,1.000000,-17.261371,2.330000,14.332000,9.886000,-1.559204,1.180000,0.000000
25%,1.681500,53.095000,47.949000,-9.553367,-1.048000,-1.029167,-1.001000,-1.134500,23.600000,2.000000,42.421241,6.209000,37.716500,32.423500,2.555000,5.024243,0.000000
50%,3.501500,60.689162,64.315000,-3.716039,-0.491000,-0.491000,-0.535378,-0.408917,32.400000,3.946133,89.884667,8.212000,50.261000,50.290000,6.638548,6.317390,0.000000
75%,5.204000,65.944235,94.747000,1.401825,0.114167,0.174500,-0.002000,0.238500,42.684691,6.000000,99.977500,11.607500,61.721000,64.983000,9.497530,7.269343,1.000000
max,22.260000,89.790000,341.464000,42.636000,1.990000,1.990000,2.328000,1.533333,92.600000,7.000000,108.459339,36.970000,92.328000,92.074000,78.175000,9.950000,1.000000

# Scaler on whole dataset

Use minmax scaler on the entire dataset

In [55]:
from sklearn.preprocessing import MinMaxScaler

In [56]:

imputed_final_df.columns

Index(['Economic growth: the rate of change of real GDP',
       'Labor force participation rate',
       'Trade openness: exports plus imports as percent of GDP',
       'Trade balance as percent of GDP',
       'Rule of law index (-2.5 weak; 2.5 strong)',
       'Government effectiveness index (-2.5 weak; 2.5 strong)',
       'Control of corruption (-2.5 weak; 2.5 strong)',
       'Political stability index (-2.5 weak; 2.5 strong)',
       'Corruption Perceptions Index 100 = no corruption',
       'Political rights index 7 (weak) - 1 (strong)',
       'Access to electricity percent of the population',
       'Death rate per 1000 people', 'Economic globalization index (0-100)',
       'Social globalization index (0-100)', 'Homicides per 100000 people',
       'Group grievance index 0 (low) - 10 (high)', 'target'],
      dtype='object')

# Creating the Model

In [57]:
model_drops = []

In [58]:
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

In [59]:
imputed_final_df.drop(columns=model_drops,inplace=True)

scaler = MinMaxScaler()
scaler.fit(imputed_final_df)
full_dataset_scaled = pd.DataFrame(scaler.transform(imputed_final_df), columns=imputed_final_df.columns)


X = full_dataset_scaled.drop(columns='target')
y = full_dataset_scaled['target']
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size = 0.3, random_state=5)

In [60]:
full_dataset_scaled

,Economic growth: the rate of change of real GDP,Labor force participation rate,Trade openness: exports plus imports as percent of GDP,Trade balance as percent of GDP,Rule of law index (-2.5 weak; 2.5 strong),Government effectiveness index (-2.5 weak; 2.5 strong),Control of corruption (-2.5 weak; 2.5 strong),Political stability index (-2.5 weak; 2.5 strong),Corruption Perceptions Index 100 = no corruption,Political rights index 7 (weak) - 1 (strong),Access to electricity percent of the population,Death rate per 1000 people,Economic globalization index (0-100),Social globalization index (0-100),Homicides per 100000 people,Group grievance index 0 (low) - 10 (high),target
0,0.339710,0.613761,0.063096,0.508234,0.229785,0.194174,0.186241,0.339652,0.155808,0.708173,0.164469,0.507737,0.073670,0.063416,0.101222,0.752153,1.0
1,0.351215,0.563137,0.112506,0.493537,0.370820,0.304261,0.253217,0.391515,0.233392,0.366667,0.351773,0.293014,0.290297,0.146931,0.103153,0.672647,1.0
2,0.354891,0.539618,0.033425,0.537367,0.287334,0.221805,0.184520,0.314752,0.163768,0.533333,0.300164,0.269400,0.068029,0.037353,0.107108,0.755819,1.0
3,0.408673,0.567835,0.078466,0.512226,0.309584,0.237549,0.213087,0.366125,0.176096,0.366667,0.244275,0.349423,0.046951,0.027084,0.101046,0.716191,1.0
4,0.083464,0.570172,0.235594,0.575545,0.488353,0.466741,0.380769,0.493645,0.408823,0.470586,0.651071,0.199423,0.502860,0.561210,0.082263,0.595254,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359,0.398870,0.631335,0.173967,0.557006,0.274977,0.393171,0.262849,0.596447,0.293144,0.333333,0.865835,0.130543,0.399097,0.600112,0.109437,0.576967,0.0
360,0.350671,0.275162,0.150079,0.446351,0.493584,0.422927,0.336760,0.612435,0.295508,0.233333,0.533145,0.174480,0.383071,0.441987,0.120190,0.530597,0.0
361,0.319491,0.439375,0.206204,0.441073,0.379468,0.443902,0.313265,0.624426,0.335697,0.166667,0.901422,0.134353,0.605980,0.659780,1.000000,0.586089,0.0
362,0.370754,0.535930,0.154848,0.620829,0.785518,0.837561,0.651493,0.460992,0.633570,0.033333,0.932713,0.081697,0.719037,0.926145,0.037113,0.994299,0.0
363,0.354891,0.543021,0.033425,0.537367,0.297316,0.220560,0.193166,0.378335,0.164107,0.533333,0.296619,0.269400,0.068029,0.037353,0.108112,0.667831,0.0

In [61]:
bst = XGBClassifier(n_estimators=100,max_depth=30,learning_rate=1, 
                    objective='binary:logistic')

In [62]:
bst.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=1, max_bin=256,
              max_cat_threshold=64, max_cat_to_onehot=4, max_delta_step=0,
              max_depth=30, max_leaves=0, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=100, n_jobs=0,
              num_parallel_tree=1, predictor='auto', random_state=0, ...)

In [63]:
preds = bst.predict(X_test)

accuracy_score(preds,y_test)
bst.predict_proba(X_test)
print(f'accuracy = {accuracy_score(preds,y_test)}')
print(f'recall = {recall_score(preds,y_test)}')
print(f'f1 = {f1_score(preds,y_test)}')

accuracy = 0.7181818181818181
recall = 0.5
f1 = 0.5079365079365079

In [64]:
import pandas as pd

features = bst.get_booster().feature_names
importances = bst.feature_importances_
feature_importances_df = pd.DataFrame(zip(features, importances), columns=['feature', 'importance']).set_index('feature')
feature_importances_df.sort_values('importance', ascending=False).head(20).keys

<bound method NDFrame.keys of                                                     importance
feature
Group grievance index 0 (low) - 10 (high)             0.258598
Political stability index (-2.5 weak; 2.5 strong)     0.114760
Corruption Perceptions Index 100 = no corruption      0.080582
Government effectiveness index (-2.5 weak; 2.5 ...    0.070241
Trade balance as percent of GDP                       0.060898
Homicides per 100000 people                           0.059430
Rule of law index (-2.5 weak; 2.5 strong)             0.057771
Economic globalization index (0-100)                  0.054578
Political rights index 7 (weak) - 1 (strong)          0.043711
Death rate per 1000 people                            0.040445
Labor force participation rate                        0.037075
Control of corruption (-2.5 weak; 2.5 strong)         0.035238
Social globalization index (0-100)                    0.030321
Trade openness: exports plus imports as percent...    0.024354
Economic growth: the rate of change of real GDP       0.018153
Access to electricity percent of the population       0.013843>

In [65]:
feature_importances_df.sort_values('importance', ascending=False).tail(20)

                                                    importance
feature
Group grievance index 0 (low) - 10 (high)             0.258598
Political stability index (-2.5 weak; 2.5 strong)     0.114760
Corruption Perceptions Index 100 = no corruption      0.080582
Government effectiveness index (-2.5 weak; 2.5 ...    0.070241
Trade balance as percent of GDP                       0.060898
Homicides per 100000 people                           0.059430
Rule of law index (-2.5 weak; 2.5 strong)             0.057771
Economic globalization index (0-100)                  0.054578
Political rights index 7 (weak) - 1 (strong)          0.043711
Death rate per 1000 people                            0.040445
Labor force participation rate                        0.037075
Control of corruption (-2.5 weak; 2.5 strong)         0.035238
Social globalization index (0-100)                    0.030321
Trade openness: exports plus imports as percent...    0.024354
Economic growth: the rate of change of real GDP       0.018153
Access to electricity percent of the population       0.013843

In [66]:
def get_imputed_df(country,year,lookback=5):
    df = get_hist_data(country,year,lookback).groupby('country_all').mean(numeric_only=True)
    df.drop(columns=[col for col in df if col not in columns_to_keep],inplace=True)
    df['target'] = 0.5
    imputed_df = pd.DataFrame(imputer.transform(df),columns=df.columns)
    imputed_df.drop(columns=model_drops,inplace=True)
    
    
    return imputed_df




def get_prob(country,year,lookback=5):
    df = get_imputed_df(country,year,lookback)
    scaled_df = pd.DataFrame(scaler.transform(df),columns=df.columns)
    scaled_df.drop(columns='target',inplace=True)
    prob = bst.predict_proba(scaled_df)[0][1]
    return prob

def prob_series(country,start_year,end_year,lookback=5):
    my_list =[]
    for year in range(start_year,end_year+1):
        my_list.append(get_prob(country,year,lookback))
    return my_list


    
prob_series('USA',1990,2020)
get_imputed_df('Iran',2019)

,Economic growth: the rate of change of real GDP,Labor force participation rate,Trade openness: exports plus imports as percent of GDP,Trade balance as percent of GDP,Rule of law index (-2.5 weak; 2.5 strong),Government effectiveness index (-2.5 weak; 2.5 strong),Control of corruption (-2.5 weak; 2.5 strong),Political stability index (-2.5 weak; 2.5 strong),Corruption Perceptions Index 100 = no corruption,Political rights index 7 (weak) - 1 (strong),Access to electricity percent of the population,Death rate per 1000 people,Economic globalization index (0-100),Social globalization index (0-100),Homicides per 100000 people,Group grievance index 0 (low) - 10 (high),target
0,2.578,42.388,45.656,0.61,-0.808,-0.292,-0.748,-0.978,28.2,6.0,99.97,4.82,26.86,57.082,3.3,8.94,0.5

In [67]:

def plot_prob_series(country,start_year,end_year,lookback=5):
    
    sns.lineplot(x = list(range(start_year,end_year+1)),y=prob_series(country,start_year,end_year,lookback))
    
#plot_prob_series('Mexico',1990,2022)

In [68]:
codes = pd.read_csv('/Users/yasmeenmahomedy2/Downloads/Conflict Datasets/country_code_example.csv')


def lambda_prob(row):
    
    prob_value = get_prob(row['Country from our model'],2021)
    
    return prob_value

code_dict = pd.Series(codes['Country from our model'].values,index=codes.Code).to_dict()

codes2 = codes[['Country from our model', 'Code']].dropna()

codes2['prob'] = codes2.apply(lambda x: lambda_prob(x),axis=1)
# codes2
# codes2['next_year_prob'] = get_prob(codes2['Country from our model'],2022)

codes2 = codes[['Country from our model', 'Code']].dropna()
code_dict_2 = dict(zip(code_dict.values(),code_dict.keys()))
code_dict_2['USA'] = 'USA'
code_dict_2['Uruguay'] = 'URY'

In [69]:

def get_year_probs(year):
    def lambda_prob(row):
    
        prob_value = get_prob(row['Country from our model'],year)
    
        return prob_value
    codes3 = codes[['Country from our model', 'Code']].dropna()
    
    codes3[year] = codes3.apply(lambda x: lambda_prob(x),axis=1)
    return codes3

get_year_probs(1990)

time_series_probs = [get_year_probs(i) for i in range(1990,2023)]

In [70]:
time_series_large = time_series_probs[0]

for i in range(1,len(time_series_probs)):
    time_series_large = pd.merge(time_series_large,time_series_probs[i],on=['Country from our model','Code'])

In [71]:
time_series_large

,Country from our model,Code,1990,1991,1992,1993,1994,1995,1996,1997,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Afghanistan,AFG,0.803428,0.906573,0.925497,0.914452,0.906573,0.904505,0.776539,0.920187,...,0.212551,0.049097,0.980907,0.510171,0.268328,0.037876,0.067701,0.024761,0.989497,0.959587
1,Albania,ALB,0.988803,0.938125,0.573972,0.864048,0.052387,0.001792,0.001217,0.000238,...,0.000277,0.000393,0.000821,0.004818,0.008717,0.098508,0.022776,0.022776,0.056114,0.057035
2,Algeria,DZA,0.954389,0.978439,0.990014,0.991417,0.996883,0.996500,0.984383,0.995519,...,0.006306,0.005049,0.004731,0.101460,0.182110,0.034197,0.035551,0.119253,0.605704,0.460346
3,Angola,AGO,0.224448,0.000236,0.000304,0.000250,0.000906,0.001162,0.000568,0.352562,...,0.831216,0.822317,0.703294,0.775039,0.685476,0.970688,0.912779,0.945668,0.420565,0.148218
4,Argentina,ARG,0.606313,0.125165,0.125165,0.261753,0.082305,0.006665,0.011316,0.004371,...,0.000381,0.003286,0.000129,0.002249,0.009725,0.011757,0.003484,0.027183,0.004767,0.007835
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,Venezuela,VEN,0.134444,0.155053,0.014423,0.017122,0.005869,0.007468,0.009487,0.008804,...,0.427496,0.975515,0.813636,0.022156,0.052082,0.013374,0.052972,0.035616,0.036873,0.282176
171,Vietnam,VNM,0.942864,0.945741,0.797755,0.748997,0.508699,0.191110,0.489074,0.095609,...,0.686233,0.764748,0.835101,0.835101,0.131899,0.036296,0.154087,0.170828,0.170828,0.158105
172,Yemen,YEM,0.001068,0.723755,0.758464,0.777537,0.027762,0.009539,0.011013,0.097371,...,0.903587,0.819794,0.509853,0.864743,0.456908,0.218941,0.037049,0.030499,0.044107,0.072547
173,Zambia,ZMB,0.062127,0.031845,0.099673,0.065215,0.029256,0.046038,0.013899,0.001499,...,0.009892,0.012428,0.013876,0.025300,0.019061,0.008496,0.010010,0.007470,0.597735,0.437200
174,Zimbabwe,ZWE,0.860752,0.937792,0.838360,0.907073,0.965397,0.873530,0.649543,0.077585,...,0.828747,0.910620,0.952775,0.954155,0.939280,0.870471,0.710554,0.412313,0.115057,0.296907

In [72]:
time_series_probs[10]

    Country from our model Code      2000
0              Afghanistan  AFG  0.741617
1                  Albania  ALB  0.000126
2                  Algeria  DZA  0.997183
3                   Angola  AGO  0.882322
4                Argentina  ARG  0.047743
..                     ...  ...       ...
170              Venezuela  VEN  0.011720
171                Vietnam  VNM  0.006536
172                  Yemen  YEM  0.096277
173                 Zambia  ZMB  0.001354
174               Zimbabwe  ZWE  0.124663

[175 rows x 3 columns]

In [73]:
def plot_feature_series(country,feature,lookback=5):
    years = list(range(1990,2023))
    series = [get_imputed_df(country, i, lookback)[feature][0] for i in years]
    return sns.lineplot(x=years,y=series)


#plot_feature_series('Iran','Control of corruption (-2.5 weak; 2.5 strong)')

# Downloading the data

In [74]:
csv_full['year_all'] = csv_full.apply(lambda x: get_year(x),axis=1)

In [75]:

codes2.head()

  Country from our model Code
0            Afghanistan  AFG
1                Albania  ALB
2                Algeria  DZA
3                 Angola  AGO
4              Argentina  ARG

In [76]:
list_of_full_dfs = []

for country in codes2['Country from our model']:
    df = get_imputed_df(country,1990) 
    df['country'] = country
    df['year'] = 1990
    list_of_full_dfs.append(df)

In [77]:
list_of_fuller_dfs = []

In [78]:
for df in list_of_full_dfs:
    
    country = df['country'][0]
    for year in range(1991,2023):
        new_year_df = get_imputed_df(country,year)
        new_year_df['country'] = country
        new_year_df['year'] = year
        
        df = pd.concat([df,new_year_df])
        
    list_of_fuller_dfs.append(df)

In [79]:
monster_df= list_of_fuller_dfs[0]

for i in range(1,len(list_of_fuller_dfs)):
    monster_df = pd.concat([monster_df,list_of_fuller_dfs[i]])

In [80]:
list_of_full_dfs[1]

,Economic growth: the rate of change of real GDP,Labor force participation rate,Trade openness: exports plus imports as percent of GDP,Trade balance as percent of GDP,Rule of law index (-2.5 weak; 2.5 strong),Government effectiveness index (-2.5 weak; 2.5 strong),Control of corruption (-2.5 weak; 2.5 strong),Political stability index (-2.5 weak; 2.5 strong),Corruption Perceptions Index 100 = no corruption,Political rights index 7 (weak) - 1 (strong),Access to electricity percent of the population,Death rate per 1000 people,Economic globalization index (0-100),Social globalization index (0-100),Homicides per 100000 people,Group grievance index 0 (low) - 10 (high),target,country,year
0,3.01,57.147526,35.34,-1.726,-1.235113,-1.128261,-1.065362,-1.345141,22.401866,7.0,61.432836,5.876,23.976,32.206,10.032213,7.870577,0.5,Albania,1990

In [81]:


def get_year(row):
    
    year_value = row['CountryYear'][-4:]
    
    return int(year_value)

In [82]:
master_df.head()

def prob_for_master_df(row):
    
    prob = get_prob(row['country'],row['year'])
    
    return prob

master_df['prob'] = master_df.apply(lambda x: prob_for_master_df(x),axis=1)

In [83]:
master_df['code'] = master_df['country'].map(code_dict_2)

In [86]:
master_df.to_csv('full_feature_test_new.csv')